### ISSUE TITLE
autobattle关于开启CUDA加速后无法读取时间

### ISSUE THREAD

**Issue by Vinzelles** [Gibberer/pcr-script#9]
安装easyocr的时候自动安装的torch经过输入`print(torch.__version__)`查看发现是x.x.x+cpu版本，运行的时候提示无法使用GPU加速，`torch.cuda.is_available()`返回false，**此时可以正确读取时间，点击也可以打印日志，但是会有0.5秒左右延迟。**

手动删除torch依赖包并到官网下载cuda11.3的版本
`pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio===0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`
之后，`torch.cuda.is_available()`返回true，运行battle.py也可以正确调用GPU了，**但是却没有办法读取时间，点击也不打印日志**

![QQ截图20211214135624](https://user-images.githubusercontent.com/67829622/145941538-6888d36e-f31f-43e5-8387-42ef752cf3c7.png)

想请教下大佬是为啥

**Comment by AlphaBoom** [comment]
只安装了torch的cuda版本吧？打开powerShell输入命令确认下cuda是否安装
```
nvcc -V
```

**Comment by Vinzelles** [comment]
![J3H)W6O37N7A85ZW WYANCA](https://user-images.githubusercontent.com/67829622/146106815-906edf7c-d447-4393-b4e7-a168ce9152d2.png)
cuda是正确安装了的，cudnn也装了，任务管理器里有显示调用GPU
![0 XG(IUV1D9ULJG5 H_~3F8](https://user-images.githubusercontent.com/67829622/146106916-7e3e58b3-9657-43d6-94c8-dc68d674fa67.png)

**Comment by AlphaBoom** [comment]
CPU模式无问题那可以确保获取时间的坐标位置无误，可以尝试跑下easyOCR的示例代码在开启GPU的情况，看是否有能够正常识别文本。

**Comment by Vinzelles** [comment]
大佬方便留个联系方式吗？想和您详细请教一下，可以有偿

**Comment by AlphaBoom** [comment]
有问题就在issue里说就好了

**Comment by Vinzelles** [comment]
换了一台电脑配置后，cuda加速的ocr可以使用了，程序可以正确进入打轴流程，但是识别精度非常感人，打的轴基本是不可用状态
想问一下有别的方式实现吗？我看到您在文档写了使用90张模板图片进行余弦相似度判断，我是繁中版玩家，已经按照原来images/time文件夹里的时间图片格式截了90张32x20的png图片替换，但是关闭ocr开关后运行会报这个错误

![GN4VF8@BDCJ}%$6(U4 74J3](https://user-images.githubusercontent.com/67829622/146147818-53c752bd-65b1-4927-a01f-e10219578043.png)

没有任何读取到时间的输出，点击可以打印log

**Comment by AlphaBoom** [comment]
```python3
    def _readtime_from_template(self, screenshot, left, top, right, bottom):
        start = time.time()
        roi = self._roi(left, top, right, bottom)
        img = screenshot[roi[1]:roi[3], roi[0]:roi[2]]
        cur = None
        cur_max_value = 0
        for i in range(1, 91):
            ret = self._similar(img, f"{i}", directory="autobattle/images/time")
            if ret > cur_max_value:
                cur_max_value = ret
                cur = i
        if cur_max_value < 0.9:
            return None
        return int(cur)
```
```python3
if cur_max_value < 0.9:
      return None
```
当相似度过低的时候会直接返回None，可以在这里确定下是否是生成的模板图片有问题。

通过余弦相似度匹配的图片需要完全一致才能用，最好通过程序来生成图片。

PS. 生成模板图片可以借助下OCR。先用开启OCR的模式跑一遍生成模板图。类似下面这么操作
```python3
_last_seconds = 0

def _readtime(self, screenshot):
        if self._ocr is None:
            return self._readtime_from_template(screenshot, 809, 15, 841, 35)
        ret = self._readtext(screenshot, 809, 15, 841, 35)
        if not ret:
            return None
        text = ret[0]
        text = text.strip()
        minute, seconds = None, None
        if len(text) == 4:
            # '1.24' '1:24' '1;24'
            text = re.sub(r'[.;|]', ':', text)
            splits = text.split(":")
            if len(splits) >= 2:
                minute = splits[0]
                seconds = splits[1]
        elif len(text) == 3:
            # '124' '001'
            minute = text[:1]
            seconds = text[1:]
        if minute and seconds and minute.isdigit() and seconds.isdigit():
            # 这里写输出图片的代码
            global _last_seconds
            _total_seconds = 60 * int(minute) + int(seconds)
            if _total_seconds != _last_seconds:
                _last_seconds = _total_seconds
                roi = self._roi(809, 15, 841, 35)
                img = screenshot[roi[1]:roi[3], roi[0]:roi[2]]
                cv.imwrite(f"{_total_seconds}.png", img)
            return 60 * int(minute) + int(seconds)
        else:
            print(f"error parse:{ret[0]}")
            return None
```

**Comment by Vinzelles** [comment]
`已选择Do Nothing, 按r恢复运行
>? r
执行恢复操作
剩余时间: 90
剩余时间: 89
剩余时间: 88
剩余时间: 87
剩余时间: 86
剩余时间: 85
剩余时间: 84
error parse:1223
剩余时间: 82
Error:84 - 82中的时间未解析到
剩余时间: 81
剩余时间: 80
剩余时间: 79
剩余时间: 78
error parse:I:1
剩余时间: 76
Error:78 - 76中的时间未解析到
剩余时间: 75
剩余时间: 74
剩余时间: 73
剩余时间: 72
剩余时间: 70
Error:72 - 70中的时间未解析到
error parse:1o9
error parse:LoB
error parse:4oB
剩余时间: 67
Error:70 - 67中的时间未解析到
剩余时间: 66
error parse:L05
剩余时间: 64
Error:66 - 64中的时间未解析到
error parse:L03
剩余时间: 62
Error:64 - 62中的时间未解析到
剩余时间: 61
error parse:I:o0
剩余时间: 59
Error:61 - 59中的时间未解析到
读取到错误的时间，期望:58,实际读取:178
读取到错误的时间，期望:58,实际读取:178
剩余时间: 57
Error:59 - 57中的时间未解析到
剩余时间: 56
剩余时间: 55
剩余时间: 54
剩余时间: 53
剩余时间: 52
读取到错误的时间，期望:51,实际读取:171
读取到错误的时间，期望:51,实际读取:171
error parse:J:5o
error parse:J49
读取到错误的时间，期望:51,实际读取:168
读取到错误的时间，期望:51,实际读取:168
error parse:J:47
读取到错误的时间，期望:51,实际读取:166
读取到错误的时间，期望:51,实际读取:166
读取到错误的时间，期望:51,实际读取:45
error parse:J.44
读取到错误的时间，期望:51,实际读取:43
读取到错误的时间，期望:51,实际读取:43
error parse:J:42
error parse:J:41
error parse:J:40
error parse:).39
读取到错误的时间，期望:51,实际读取:158
error parse:).37
error parse:).36
error parse:).35
读取到错误的时间，期望:51,实际读取:34
读取到错误的时间，期望:51,实际读取:33
读取到错误的时间，期望:51,实际读取:152
读取到错误的时间，期望:51,实际读取:31
读取到错误的时间，期望:51,实际读取:30
error parse:J:19
error parse:J:18
error parse:J:17
error parse:J:16
error parse:J:15
error parse:J:14
error parse:J:13
error parse:J:12
error parse:J:1
error parse:J:10
error parse:J.09
读取到错误的时间，期望:51,实际读取:128
error parse:J.07
读取到错误的时间，期望:51,实际读取:126
error parse:2 05
error parse:J.04
error parse:2 03
error parse:J.02
error parse:J.01`


![E5J~M`R~9%WV24R4GZGXX H](https://user-images.githubusercontent.com/67829622/146180168-afc5b44d-f20e-403a-bb3b-5460fc7622f6.png)

。。。因为ocr识别率捉急导致好多时间都没截到怎么办呢，我尝试在else那边也加了输出图片的语句，最后还是有6张图片缺失
是不是应该写成定时截图呢？我是做前端的，以前没有接触过python，请大佬赐教。。。

**Comment by AlphaBoom** [comment]
这OCR没这么差的啊，我觉得你可以先检查下截出来的图片有没有问题，有可能截取时间区域的位置存在偏差导致时间的部分被切割了。

实在不行的话，可以把设置里的点击时间间隔设置为 1s。这样每隔1s会调用一次 _run 方法里面的代码，然后在下面代码的地方写下输出图片的代码就好了

```python3
    def _run(self):
            ...
            self._errorcheck(screenshot)
            # 在这下面写输出图片的逻辑
            last_seconds = remain_seconds
            if not remain_seconds or starttime - last_readtime >= LONG_INTERVAL:
```

**Comment by Vinzelles** [comment]
因为繁中版数字字体比较宽，虽然图片看起来是刚好挤得下时间数字，后来去easyocr的仓库看到了类似的issue说调整缩放，我就把裁剪的图片长宽扩大了10像素，准确度确实高了不少，但是还是有七八个时间点没有办法正确识别。
最后是0.5秒调用一次输出图片的代码生成模板图片替换后，终于可以全部正确识别了，感谢大佬

测试后发现打轴延迟在0.1秒左右

**Comment by Vinzelles** [comment]
> 这OCR没这么差的啊，我觉得你可以先检查下截出来的图片有没有问题，有可能截取时间区域的位置存在偏差导致时间的部分被切割了。
> 
> 实在不行的话，可以把设置里的点击时间间隔设置为 1s。这样每隔1s会调用一次 _run 方法里面的代码，然后在下面代码的地方写下输出图片的代码就好了
> 
> ```python
>     def _run(self):
>             ...
>             self._errorcheck(screenshot)
>             # 在这下面写输出图片的逻辑
>             last_seconds = remain_seconds
>             if not remain_seconds or starttime - last_readtime >= LONG_INTERVAL:
> ```

大佬有考虑轴提取器增加读取帧轴不

**Comment by AlphaBoom** [comment]
> > 这OCR没这么差的啊，我觉得你可以先检查下截出来的图片有没有问题，有可能截取时间区域的位置存在偏差导致时间的部分被切割了。
> > 实在不行的话，可以把设置里的点击时间间隔设置为 1s。这样每隔1s会调用一次 _run 方法里面的代码，然后在下面代码的地方写下输出图片的代码就好了
> > ```python
> >     def _run(self):
> >             ...
> >             self._errorcheck(screenshot)
> >             # 在这下面写输出图片的逻辑
> >             last_seconds = remain_seconds
> >             if not remain_seconds or starttime - last_readtime >= LONG_INTERVAL:
> > ```
> 
> 大佬有考虑轴提取器增加读取帧轴不

目前没有计划，并且如果做这块功能的话，在判断哪个角色是否释放了UB这块还没有想到策略解决。
